version: 0.2

phases:
  install:
    runtime-versions:
     nodejs: 14
  pre_build:
    commands:
      - echo install dependencies
      - npm install
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo build docker image and tag it
      - docker build -t nodejsdemo:latest .
      - docker tag nodejsdemo:latest 874913666592.dkr.ecr.us-east-1.amazonaws.com/nodejsdemo:latest
  post_build:
    commands:
      - echo push the image to ECR
      - docker push 874913666592.dkr.ecr.us-east-1.amazonaws.com/nodejsdemo:latest
      - printf '[{"name":"%s","imageUrl":"%s"}]' nodejsdemo 874913666592.dkr.ecr.us-east-1.amazonaws.com/nodejsdemo:latest > imagedefinitions.json 
artifacts:
 files:
    - imagedefinitions.json